image: docker:latest

stages : 
  - deployment
  
dockerbuild : 
   stages: package
   script: 
      - docker build -t nginx-test:1.0.0 .
      - docker run nginx-test
     
deploy : 
    stage : deploy
    image : 
    script : 
